/*
	Copyright © Bryan Apellanes 2015  
*/

using System.Reflection;
using Bam.Data.FirebirdSql;
using Bam.DependencyInjection;
using Bam.Services;

namespace Bam.Data
{
    public class FirebirdSqlSqlStringBuilder : SchemaWriter
    {
        public FirebirdSqlSqlStringBuilder()
            : base()
        {
            GoText = ";\r\n";
            CreateTableFormat = "CREATE TABLE {0} ({1})";
            AddForeignKeyColumnFormat = "ALTER TABLE {0} ADD CONSTRAINT {1} FOREIGN KEY (\"{2}\") REFERENCES {3} (\"{4}\")";
            TableNameFormatter = (s) => "\"{0}\"".Format(s);
            ColumnNameFormatter = (s) => "\"{0}\"".Format(s);
        }
        protected override RowCapSyntax RowCap => RowCapSyntax.FirebirdFirst;

        public override SqlStringBuilder Id(string idAs)
        {
            Builder.AppendFormat(" RETURNING \"Id\" AS \"{0}\"{1}", idAs, this.GoText);
            return this;
        }
        public override void Reset()
        {
            base.Reset();
            this.GoText = ";\r\n";
        }
        public static void Register(DependencyProvider incubator)
        {
            FirebirdSqlSqlStringBuilder builder = new FirebirdSqlSqlStringBuilder();
            incubator.Set(typeof(SqlStringBuilder), builder);
            incubator.Set<SqlStringBuilder>(builder);
        }
        public override string GetKeyColumnDefinition(KeyColumnAttribute keyColumn)
        {
            return string.Format("\"{0}\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", keyColumn.Name);
        }
        public override string GetColumnDefinition(ColumnAttribute column)
        {
            if ("vector".Equals(column.DbDataType, StringComparison.OrdinalIgnoreCase))
            {
                throw new NotSupportedException($"{this.GetType().Name} does not support vector columns: declared as {column.Name}.");
            }
            if ("uuid[]".Equals(column.DbDataType, StringComparison.OrdinalIgnoreCase))
            {
                throw new NotSupportedException($"{this.GetType().Name} does not support uuid[] columns: declared as {column.Name}.");
            }
            string max = string.Format("({0})", column.MaxLength);
            string type = column.DbDataType.ToLowerInvariant();

            if (type.Equals("bigint"))
            {
                type = "BIGINT";
                max = "";
            }
            else if (type.Equals("int"))
            {
                type = "INT";
                max = "";
            }
            else if (type.Equals("bit"))
            {
                type = "boolean";
                max = "";
            }
            else if (type.Equals("decimal"))
            {
                max = string.Format("({0}, 2)", column.MaxLength);
            }
            else if (type.Equals("datetime"))
            {
                type = "timestamp";
                max = "";
            }
            else if (type.Equals("varbinary"))
            {
                type = "BLOB SUB_TYPE BINARY";
                max = "";
            }
            else if (type.Equals("serial"))
            {
                max = "";
            }
            else if (type.Equals("jsonb"))
            {
                // storage/retrieval degrade only - no JSON querying. DEFAULT on a
                // BLOB SUB_TYPE TEXT column is honored by Firebird (verified against
                // Firebird 4.0: omitted-value inserts take the default).
                type = "BLOB SUB_TYPE TEXT";
                max = "";
            }

            return string.Format("{0} {1}{2}{3}{4}", ColumnNameFormatter(column.Name), type, max, GetColumnDefaultClause(column), column.AllowNull ? "" : " NOT NULL");
        }
        public override SqlStringBuilder Where(IQueryFilter filter)
        {
            WhereFormat where = FirebirdSqlFormatProvider.GetWhereFormat(filter, StringBuilder, NextNumber);
            NextNumber = where.NextNumber;
            this.parameters.AddRange(where.Parameters);
            return this;
        }
        public override SqlStringBuilder Update(string tableName, params AssignValue[] values)
        {
            Builder.AppendFormat("UPDATE {0} ", TableNameFormatter(tableName));
            SetFormat set = FirebirdSqlFormatProvider.GetSetFormat(tableName, StringBuilder, NextNumber, values);
            NextNumber = set.NextNumber;
            this.parameters.AddRange(set.Parameters);
            return this;
        }

        public override ISqlStringBuilder Select(string tableName, params string[] columnNames)
        {
            return base.Select(tableName, columnNames);
        }

        protected override void WriteCreateTable(Type daoType)
        {
            ColumnAttribute[] columns = GetColumns(daoType);

            Builder.AppendFormat(CreateTableFormat,
                TableNameFormatter(Dao.TableName(daoType)),
                columns.ToDelimited(c =>
                {
                    if (c is KeyColumnAttribute)
                    {
                        return GetKeyColumnDefinition((KeyColumnAttribute)c);
                    }
                    else
                    {
                        return GetColumnDefinition(c);
                    }
                }));
        }

        /// <summary>
        /// Writes one CREATE INDEX statement with Firebird syntax, where sort direction is
        /// declared at the index level (<c>CREATE [UNIQUE] [DESCENDING] INDEX</c>), not per
        /// column. All columns must share one direction: an index whose columns are all
        /// <see cref="SortOrder.Descending"/> renders <c>DESCENDING</c>; any mix of descending
        /// with ascending or unspecified columns fails fast. Index names are not truncated:
        /// Firebird 4+ limits identifiers to 63 characters (31 before 4.0), so declare an
        /// explicit <see cref="IndexAttribute.Name"/> when a derived
        /// <c>ix_{table}_{columns}</c> name would exceed the server's limit.
        /// </summary>
        /// <param name="index">The index to write.</param>
        /// <exception cref="NotSupportedException">
        /// Thrown when the definition carries access-method options, or mixes descending with
        /// non-descending columns.
        /// </exception>
        protected override void WriteCreateIndex(IndexDefinition index)
        {
            if (index.HasAccessMethodOptions)
            {
                throw new NotSupportedException($"{this.GetType().Name} does not support index access-method options (access method, operator class, or storage parameters): declared by index {index.Name} on {index.TableName}.");
            }
            bool anyDescending = index.Columns.Any(column => column.Order == SortOrder.Descending);
            bool allDescending = index.Columns.All(column => column.Order == SortOrder.Descending);
            if (anyDescending && !allDescending)
            {
                throw new NotSupportedException($"{this.GetType().Name} supports one sort direction per index (Firebird declares direction at the index level): index {index.Name} on {index.TableName} mixes descending with non-descending columns. Mark every column Descending or none.");
            }
            string columnList = string.Join(", ", index.Columns.Select(column => ColumnNameFormatter(column.ColumnName)));
            Builder.AppendFormat("CREATE {0}{1}INDEX {2} ON {3} ({4})",
                index.Unique ? "UNIQUE " : string.Empty,
                allDescending ? "DESCENDING " : string.Empty,
                index.Name,
                TableNameFormatter(index.TableName),
                columnList);
        }

        protected override void WriteDropForeignKeys(Type daoType)
        {
            TableAttribute table = null!;
            if (daoType.HasCustomAttributeOfType<TableAttribute>(out table))
            {
                PropertyInfo[] properties = daoType.GetProperties();
                foreach (PropertyInfo prop in properties)
                {
                    ForeignKeyAttribute fk = null!;
                    if (prop.HasCustomAttributeOfType<ForeignKeyAttribute>(out fk))
                    {
                        Builder.AppendFormat("ALTER TABLE {0} DROP CONSTRAINT {1}", TableNameFormatter(table.TableName), fk.ForeignKeyName);
                        Go();
                    }
                }
            }
        }

        public override SchemaWriter WriteDropTable(string tableName)
        {
            Builder.AppendFormat("DROP TABLE IF EXISTS {0}", TableNameFormatter(tableName));
            Go();
            return this;
        }
    }
}
