<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\bam.base\bam.base\bam.base.csproj" />
    <ProjectReference Include="..\..\bam.configuration\bam.configuration\bam.configuration.csproj" />
    <ProjectReference Include="..\bam.data\bam.data.csproj" />
  </ItemGroup>

</Project>
